version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=monitor port=5432 sslmode=disable"
    depends_on:
      - db
    ports:
      - "8080:8080"

  pinger:
    build:
      context: ./pinger
      dockerfile: Dockerfile
    environment:
      TARGET_IPS: "192.168.0.101,192.168.0.102"
      BACKEND_URL: "http://backend:8080"
      PING_INTERVAL: "30"  
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  
    depends_on:
      - backend

volumes:
  db_data:

